package org.koitharu.kotatsu.list.ui.adapter

enum class ListItemType {

	FILTER_SORT,
	FILTER_TAG,
	HEADER,
	MANGA_LIST,
	MANGA_LIST_DETAILED,
	MANGA_GRID,
	MANGA_NESTED_GROUP,
	FOOTER_LOADING,
	FOOTER_ERROR,
	STATE_LOADING,
	STATE_ERROR,
	STATE_EMPTY,
	EXPLORE_BUTTONS,
	EXPLORE_SOURCE_GRID,
	EXPLORE_SOURCE_LIST,
	EXPLORE_SUGGESTION,
	TIP,
	HINT_EMPTY,
	PAGE_THUMB,
	FEED,
	DOWNLOAD,
	CATEGORY_LARGE,
	MANGA_SCROBBLING,
	NAV_ITEM,
}
