blank_issues_enabled: false
contact_links:
    - name: ⚠️ Source issue
      url: https://github.com/KotatsuApp/kotatsu-parsers/issues/new
      about: If you have troubles with a manga parser or want to propose new manga source, please open an issue in the kotatsu-parsers repository instead