blank_issues_enabled: false
contact_links:
    - name: ⚠️ Source issue
      url: https://github.com/KotatsuApp/kotatsu-parsers/issues/new
      about: Issues and requests for sources should be opened in the kotatsu-parsers repository instead