name: 🐞 Bug report
description: Report a bug in Kotatsu
labels: [bug]
body:

    - type: textarea
      id: summary
      attributes:
          label: Brief summary
          description: Please describe, what went wrong
      validations:
          required: true

    - type: textarea
      id: reproduce-steps
      attributes:
          label: Steps to reproduce
          description: Please provide a way to reproduce this issue. Screenshots or videos can be very helpful
          placeholder: |
              Example:
                1. First step
                2. Second step
                3. Issue here
      validations:
          required: false


    - type: input
      id: kotatsu-version
      attributes:
          label: Kotatsu version
          description: You can find your Kotatsu version in **Settings → About**.
          placeholder: |
              Example: "3.3"
      validations:
          required: true

    - type: input
      id: android-version
      attributes:
          label: Android version
          description: You can find this somewhere in your Android settings.
          placeholder: |
              Example: "12.0"
      validations:
          required: true

    - type: input
      id: device
      attributes:
          label: Device
          description: List your device and model.
          placeholder: |
              Example: "LG Nexus 5X"
      validations:
          required: false

    - type: checkboxes
      id: acknowledgements
      attributes:
          label: Acknowledgements
          options:
              - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
                required: true