name: ⭐ Feature request
description: Suggest a new idea how to improve Kotatsu
labels: [feature request]
body:

    - type: textarea
      id: feature-description
      attributes:
          label: Describe your suggested feature
          description: How can Kotatsu be improved?
          placeholder: |
              Example:
                "It should work like this..."
      validations:
          required: true

    - type: checkboxes
      id: acknowledgements
      attributes:
          label: Acknowledgements
          description: Read this carefully, we will close and ignore your issue if you skimmed through this.
          options:
              - label: This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
                required: true
